[package]
name        = "flix-glsl-lib"
description = "test"
version     = "0.1.0"
flix        = "0.72.0"
authors     = ["Tomasz Sobieszek <tom.sobieszek@gmail.com>"]
repository  = "github:tsobieszek/flix-glsl-lib"
[dependencies]
